import { sidecarInvoke } from "./sidecar";

/** All Rust command names from the original Tauri app — proxied to the sidecar. */
const SIDECAR_COMMANDS = new Set([
  "analyze_audio_librosa",
  "send_message",
  "stream_chat",
  "get_thread_messages",
  "create_thread",
  "delete_thread",
  "delete_threads",
  "rename_thread",
  "list_threads",
  "toggle_thread_pinned",
  "set_thread_project",
  "assign_threads_project",
  "set_thread_color",
  "set_threads_color",
  "list_projects",
  "create_project",
  "update_project",
  "toggle_project_starred",
  "toggle_project_pinned",
  "delete_project",
  "clear_thread_messages",
  "clear_all_conversations",
  "delete_last_assistant_message",
  "delete_messages_from",
  "delete_message",
  "stop_streaming",
  "list_local_models",
  "download_model",
  "download_model_bundle",
  "delete_model",
  "get_model_info",
  "list_registry_models",
  "get_settings",
  "save_settings",
  "import_profile_picture",
  "open_models_dir",
  "set_app_pin",
  "clear_app_pin",
  "verify_app_pin",
  "has_app_pin",
  "get_hardware_snapshot",
  "restart_inference_engine",
  "preload_chat_model",
  "get_llama_runtime_info",
  "download_llama_runtime",
  "download_cudart_runtime",
  "remove_llama_runtime",
  "fetch_gallery_images",
  "fetch_nano_banana_page",
  "download_image_to_downloads",
  "fetch_sora_gallery_page",
  "fetch_sora_prompt",
  "fetch_midjourney_gallery_page",
  "get_receipt_vision_status",
  "get_receipts_folder",
  "list_receipt_images",
  "delete_receipt_image",
  "import_receipt_image",
  "preload_receipt_vision_model",
  "extract_receipt_vision",
  "list_tasks",
  "get_task_stats",
  "create_task",
  "update_task",
  "delete_task",
  "toggle_task_completed",
  "move_task_due_date",
]);

export function isSidecarCommand(cmd: string): boolean {
  return SIDECAR_COMMANDS.has(cmd);
}

export { sidecarInvoke };
